---
- name: Ansible role for installation of tomcat
  hosts: backendservers
  become: true
  become_user: root
  gather_facts: true
  tasks:
    - name: apt-get update
      apt:
        update_cache: true

    - name: Install JDK
      apt:
        name: openjdk-8-jdk

    - name: Add tomcat user group
      group:
        name: tomcat
        state: present

    - name: Add tomcat user
      user:
        name: tomcat
        groups: tomcat
        shell: /bin/false

    - name: Download tomcat
      get_url:
        url: http://mirrors.gigenet.com/apache/tomcat/tomcat-8/v8.5.39/bin/apache-tomcat-8.5.39.tar.gz
        dest: /tmp/apache-tomcat-8.5.39.tar.gz
        mode: o=rw

    - name: Create tomcat directory
      file:
        path: /opt/tomcat
        state: directory
        mode: 0777

    - name: Extract tar file
      command: /bin/tar xzvf apache-tomcat-8*tar.gz -C /opt/tomcat --strip-components=1
