---
 - name: add java8 repo
   command: add-apt-repository ppa:webupd8team/java

 - name: apt update
   apt:
    update_cache: true

 - name: download maven repository
   command: chdir=/home/edureka/Downloads/ wget http://apache.mirror.digitalpacific.com.au/maven/maven-3/{{ maven_version }}/binaries/apache-maven-{{ maven_version }}-bin.tar.gz

 - name: extract maven tar
   command: chdir=/opt /bin/tar -xzvf /home/edureka/Downloads/apache-maven-{{ maven_version }}-bin.tar.gz


 - name: install maven
   command: update-alternatives --install /usr/bin/mvn maven /opt/apache-maven-{{ maven_version }}/bin/mvn 1001
